### ISSUE TITLE
Package rasing a Type error

### ISSUE THREAD

**Issue by dauntless23** [rooneysh/Labelme2YOLO#12]
Converting 0006.json for train ...
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\Compressed\Labelme2YOLO-main\Labelme2YOLO-main\labelme2yolo.py", line 228, in <module>
    convertor.convert(val_size=args.val_size)
  File "C:\Users\Administrator\Downloads\Compressed\Labelme2YOLO-main\Labelme2YOLO-main\labelme2yolo.py", line 97, in convert
    img_path = self._save_yolo_image(json_data,
  File "C:\Users\Administrator\Downloads\Compressed\Labelme2YOLO-main\Labelme2YOLO-main\labelme2yolo.py", line 194, in _save_yolo_image
    img = utils.img_b64_to_arr(json_data['imageData'])
  File "C:\ProgramData\anaconda3\lib\site-packages\labelme\utils\image.py", line 24, in img_b64_to_arr
    img_data = base64.b64decode(img_b64)
  File "C:\ProgramData\anaconda3\lib\base64.py", line 80, in b64decode
    s = _bytes_from_decode_data(s)
  File "C:\ProgramData\anaconda3\lib\base64.py", line 45, in _bytes_from_decode_data
    raise TypeError("argument should be a bytes-like object or ASCII "
TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'

**Comment by rooneysh** [comment]
That's because your Labelme json format is not bytes, check if your Labelme version is match the requirements. Since this 'utils.img_b64_to_arr' code is provided by Labelme.

**Comment by wzm2256** [comment]
Hi, if you are still working on this. A solution is here https://github.com/wzm2256/Labelme2YOLO/tree/wzm2256-patch-1   
I removed the labelme dependency, and now it should work with all labelme versions.

**Comment by PengPeng-JunJun** [comment]
I also have same question.After check the json files,I find not every img has datas in imageData.
So I get other way to slove it.You can copy the imgs to your dataset image floder install of use data to get image.
