### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by gerlis22** [rooneysh/Labelme2YOLO#14]
Hi, I'm trying to install the `requirements.txt `on a MacOS Arm64 using `pip install -r requirements.txt` and get the following error:

> Collecting PyQt5!=5.15.3,!=5.15.4 (from labelme>=4.5.0->-r requirements.txt (line 7))
  Using cached PyQt5-5.15.10.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
   × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Querying qmake about your Qt installation...
      Traceback (most recent call last):
        File "/Users/gerardocelis/miniconda3/envs/cameratraps-detector/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/gerardocelis/miniconda3/envs/cameratraps-detector/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/gerardocelis/miniconda3/envs/cameratraps-detector/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/h7/79_xs8tx5bx_ykgdf0cx722m0000gp/T/pip-build-env-1uhuy18q/overlay/lib/python3.8/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/private/var/folders/h7/79_xs8tx5bx_ykgdf0cx722m0000gp/T/pip-build-env-1uhuy18q/overlay/lib/python3.8/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/h7/79_xs8tx5bx_ykgdf0cx722m0000gp/T/pip-build-env-1uhuy18q/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 602, in setup
          self.update(tool)
        File "project.py", line 165, in update
      sipbuild.exceptions.UserException
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Any ideas how to install?

**Comment by rooneysh** [comment]
PyQT is required by Labelme, if there's problem about it, you can try to install PyQT or PySide before pip install requirements.txt.
